---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oke-fss-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: 
    path: /data/sport/data/input
  csi:
    driver: fss.csi.oraclecloud.com
    volumeHandle: ocid1.filesystem.oc1.ap_se
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oke-fss-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: oke-fss-pv